### ISSUE TITLE
schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326)

### ISSUE THREAD

**Issue by juyeongkim** [RGLab/ImmPortR#1]
[Upload related functions](http://rglab.org/ImmPortR/reference/index.html#section-upload) produce curl errors in Windows (AppVeyor):

```
schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

**Comment by juyeongkim** [comment]
These work in Windows 10, but not in Windows 7 and Windows Server 2012. They are disabled in Windows for now.

**Comment by dhaminimohandas** [comment]
can you please tell how you resolved this problem
