### ISSUE TITLE
ImmPort Access Token Content Has Changed

### ISSUE THREAD

**Issue by johnmcampbell13** [RGLab/ImmPortR#2]
The  ImmPort team has recently changed the way an Access Token is returned.  Details can be found at this link: https://docs.immport.org/home/software_release_notes/June_2022_Software_Release/

Basically the token name was changed from "token" to "access_token". This may cause an issue with the ImmPortR code. Thank you for writing and maintaining this code, we try to promote ImmPortR to R users trying to download data from ImmPort

**Comment by juyeongkim** [comment]
@johnmcampbell13 Oh! 😅 Thank you for letting me know. I will update the token name to "access_token".

**Comment by juyeongkim** [comment]
c49671556294e2480eef64831253ffd489eb1bf1
